development:
  adapter: postgresql
  encoding: utf8
  database: release_development
  host: 
  pool: 5
  reconnect: true
  username: release
  password: release

test:
  adapter: postgresql
  encoding: utf8
  database: release_test
  host: 
  pool: 5
  reconnect: true
  username: release
  password: release
